config/routes.rb
Rails.application.routes.draw do
	root 'home#index'

  	resources :users, only: [:new, :create]
  	resources :questions
  	resources :sessions, only: [:new, :create, :destroy]
  	get 'admin', to: 'home#admin', as: 'admin'
  	post 'process_question', to: 'home#process_question', as: 'process_question'
  	get 'result', to: 'home#result', as: 'result'
	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/question.rb
class Question
  include Mongoid::Document
  field :content, type: String
  field :answer, type: String
  field :correct_answer, type: Integer
  field :wrong_answer, type: Integer
  validates :content, :answer, presence: true

  def correct_answer_text
  	"#{self.correct_answer} Users" if correct_answer
  end

   def wrong_answer_text
  	"#{self.wrong_answer} Users" if wrong_answer
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :email, type: String
  field :password_digest, type: String
  validates :email, :password, presence: true
  validates :email, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_email]
      @current_user ||= User.where(email: session[:user_email]).first
    else
      @current_user = nil
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
   before_action :authenticate_http

   def authenticate_http
    user = 'admin'
    pass = 'admin'
    authenticate_or_request_with_http_basic do |username, password|
      username == user && password == pass
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		return redirect_to login_path unless current_user
		@questions = Question.all.sample(4)
	end

	def admin
		redirect_to questions_path
	end

	def process_question
		answers = params[:answers]
		correct = []
		wrong = []

		answers.each do |k, v|
			question = Question.find_by(_id: k)
			if question.answer == v || (question.answer.to_words == v rescue false)
				question.update_attributes(correct_answer: question.correct_answer.to_i + 1)
				correct << k
			else
				question.update_attributes(wrong_answer: question.wrong_answer.to_i + 1)
				wrong << k
			end
		end

		redirect_to result_path(correct_answer: correct.size, wrong_answer: wrong.size )

	end
end

app/controllers/questions_controller.rb
class QuestionsController < BaseController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :answer)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_email] = user.email
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
  	session[:user_email] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>
<p id=”notice”><%= notice %></p><hr/>
This is an example of the question.. <br/><br/>
<%= form_tag process_question_path do %>
	<% @questions.each_with_index do |q, i| %>
		<div class="alert alert-primary" role="alert">
		  <p><%= simple_format(q.content) %></p>
		  <hr>
		   <input type="text" name="answers[<%= q._id %>]" class="form-control" placeholder="answer here" required>
		</div>
	<% end %>
	<div class="actions form-group">
	    <button type="submit" class="btn btn-primary">Submit Now!</button>
	  </div>
<% end %>
<style type="text/css">
  .wrap-login100 {
    display: block;
  }
</style>

app/views/home/result.html.erb
<% size = params[:correct_answer].to_i + params[:wrong_answer].to_i %>
<% if params[:correct_answer].to_i == size %>
	<div class="text-center">
	  <img src="https://media.giphy.com/media/P5VmnAcgCBs5y/giphy.gif" class="rounded" >
	</div><br/><br/>
   <h2>Well Done!! You are the Best!</h2>
   <br/><br/>
<% elsif params[:correct_answer].to_i >= params[:wrong_answer].to_i %>
	<div class="text-center">
	  <img src="https://thumbs.gfycat.com/BriefNauticalDairycow-max-1mb.gif" class="rounded" >
	</div>
	<br/><br/>
	<h2>Cool!! your answer is good!</h2>
	<br/><br/>
<% else %>
	<div class="text-center">
	  <img src="https://media1.tenor.com/images/5acb9fcf00014681bbbd22c338d900db/tenor.gif?itemid=10164073" class="rounded" >
	</div>
	<br/><br/>
	<h2>Whats wrong with you? Your answer is not correctly</h2>
	<br/><br/>
<% end %>

<div class="actions form-group">
	<a href="<%= root_path %>" class="btn btn-info">Back to Homepage</a>
</div>

<style type="text/css">
  .wrap-login100 {
    display: block;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuipperTest</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false %>

    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
      <link rel="stylesheet" type="text/css" href="/assets/login/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/animate.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/hamburgers.min.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/select2.min.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/util.css">
      <link rel="stylesheet" type="text/css" href="/assets/login/main.css">
  </head>

  <body>

    <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">
        <%= yield %>
      </div>
    </div>
  </div>


  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
  <script src="/assets/login/jquery-3.2.1.min.js"></script>
  <script src="/assets/login/popper.js"></script>
  <script src="/assets/login/bootstrap.min.js"></script>
  <script src="/assets/login/select2.min.js"></script>
  <script src="/assets/login/tilt.jquery.min.js"></script>
  <script >
    $('.js-tilt').tilt({
      scale: 1.1
    })
  </script>
<!--===============================================================================================-->
  <script src="/assets/login/main.js"></script>
</html>

app/views/questions/_form.html.erb
<br/><br/>
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul><br/><br/>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: "5"  %>
  </div>

  <div class="field form-group">
    <%= f.label :answer %>
    <%= f.text_field :answer, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>
<style type="text/css">
  .wrap-login100 {
    display: block;
  }
</style>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div id="content">
  <% if notice.present? %>
    <div class="alert alert-primary notice" role="alert">
     <%= notice %>
    </div>
  <% end %>

<h1>Questions</h1><br/>
<table class="table table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Content</th>
      <th>Answer</th>
      <th>Correct Answer</th>
      <th>Wrong Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.answer %></td>
        <td><%= question.correct_answer_text %></td>
        <td><%= question.wrong_answer_text %></td>
        <td><%= link_to 'Show', question, class: 'btn btn-secondary' %></td>
        <td><%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary ' %></td>
        <td><%= link_to 'Destroy', question, class: 'btn btn-danger',  method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path, class: 'btn btn-success' %>
</div>
<style type="text/css">
  .wrap-login100 {
    width: 100%;
    }
  </style>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% if notice.present? %>
    <div class="alert alert-primary notice" role="alert">
     <%= notice %>
    </div>
  <% end %>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>
<hr/>
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-success' %> |
<%= link_to 'Back', questions_path, class: 'btn btn-light'%>
<style type="text/css">
  .wrap-login100 {
    display: block;
  }
</style>

app/views/users/new.html.erb
<div class="login100-pic js-tilt" data-tilt>
  <img src="/assets/img-01.png" alt="IMG">
</div>

<%= form_for(@user, class: "login100-form validate-form") do |form| %>
  <div class="wrap-input100 validate-input">
    <span class="login100-form-title">
      Register
    </span>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li> - <%= message %></li>
        <% end %>
        </ul><br/>
      </div>
    <% end %>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
    <%= form.text_field :email, class: 'input100', type: 'email', placeholder: 'email' %>
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-envelope" aria-hidden="true"></i>
    </span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Password is required">
    <%= form.password_field :password, class: 'input100', placeholder: 'password ' %>
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-lock" aria-hidden="true"></i>
    </span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Password is required">
    <%= form.password_field :password_confirmation, class: 'input100', placeholder: 'password confirmation' %>
    <span class="focus-input100"></span>
    <span class="symbol-input100">
      <i class="fa fa-lock" aria-hidden="true"></i>
    </span>
  </div>

  <div class="container-login100-form-btn">
    <button class="login100-form-btn" type="submit">
      Submit
    </button>
  </div>

  <div class="text-center p-t-136">
    <a class="txt2" href="<%= login_path %>">
      Or Login to your account
      <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
    </a>
  </div>
<% end %>